# Generated by Django 5.2 on 2025-05-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank='true', default='', max_length=150, null='true'),
            preserve_default='true',
        ),
    ]
