# Generated by Django 5.2 on 2025-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_sale_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default='False'),
        ),
    ]
